// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: battle/v1/weapon.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateWeaponRequest) Reset() {
	*x = CreateWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeaponRequest) ProtoMessage() {}

func (x *CreateWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeaponRequest.ProtoReflect.Descriptor instead.
func (*CreateWeaponRequest) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWeaponRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWeaponReply) Reset() {
	*x = CreateWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeaponReply) ProtoMessage() {}

func (x *CreateWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeaponReply.ProtoReflect.Descriptor instead.
func (*CreateWeaponReply) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWeaponReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateWeaponRequest) Reset() {
	*x = UpdateWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeaponRequest) ProtoMessage() {}

func (x *UpdateWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeaponRequest.ProtoReflect.Descriptor instead.
func (*UpdateWeaponRequest) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWeaponRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWeaponRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateWeaponReply) Reset() {
	*x = UpdateWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeaponReply) ProtoMessage() {}

func (x *UpdateWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeaponReply.ProtoReflect.Descriptor instead.
func (*UpdateWeaponReply) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{3}
}

type DeleteWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteWeaponRequest) Reset() {
	*x = DeleteWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeaponRequest) ProtoMessage() {}

func (x *DeleteWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeaponRequest.ProtoReflect.Descriptor instead.
func (*DeleteWeaponRequest) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWeaponRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWeaponReply) Reset() {
	*x = DeleteWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeaponReply) ProtoMessage() {}

func (x *DeleteWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeaponReply.ProtoReflect.Descriptor instead.
func (*DeleteWeaponReply) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{5}
}

type GetWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWeaponRequest) Reset() {
	*x = GetWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponRequest) ProtoMessage() {}

func (x *GetWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponRequest.ProtoReflect.Descriptor instead.
func (*GetWeaponRequest) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{6}
}

func (x *GetWeaponRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetWeaponReply) Reset() {
	*x = GetWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponReply) ProtoMessage() {}

func (x *GetWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponReply.ProtoReflect.Descriptor instead.
func (*GetWeaponReply) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{7}
}

func (x *GetWeaponReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWeaponRequest) Reset() {
	*x = ListWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponRequest) ProtoMessage() {}

func (x *ListWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponRequest.ProtoReflect.Descriptor instead.
func (*ListWeaponRequest) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{8}
}

type ListWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ListWeaponReply_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListWeaponReply) Reset() {
	*x = ListWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponReply) ProtoMessage() {}

func (x *ListWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponReply.ProtoReflect.Descriptor instead.
func (*ListWeaponReply) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{9}
}

func (x *ListWeaponReply) GetData() []*ListWeaponReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListWeaponReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListWeaponReply_Data) Reset() {
	*x = ListWeaponReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_v1_weapon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeaponReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponReply_Data) ProtoMessage() {}

func (x *ListWeaponReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_battle_v1_weapon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponReply_Data.ProtoReflect.Descriptor instead.
func (*ListWeaponReply_Data) Descriptor() ([]byte, []int) {
	return file_battle_v1_weapon_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListWeaponReply_Data) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListWeaponReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_battle_v1_weapon_proto protoreflect.FileDescriptor

var file_battle_v1_weapon_proto_rawDesc = []byte{
	0x0a, 0x16, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x76, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2a,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xa7, 0x03, 0x0a, 0x06, 0x57,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x54, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x54, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f,
	0x6e, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x74, 0x65, 0x72, 0x72, 0x61, 0x72, 0x69, 0x61,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_battle_v1_weapon_proto_rawDescOnce sync.Once
	file_battle_v1_weapon_proto_rawDescData = file_battle_v1_weapon_proto_rawDesc
)

func file_battle_v1_weapon_proto_rawDescGZIP() []byte {
	file_battle_v1_weapon_proto_rawDescOnce.Do(func() {
		file_battle_v1_weapon_proto_rawDescData = protoimpl.X.CompressGZIP(file_battle_v1_weapon_proto_rawDescData)
	})
	return file_battle_v1_weapon_proto_rawDescData
}

var file_battle_v1_weapon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_battle_v1_weapon_proto_goTypes = []interface{}{
	(*CreateWeaponRequest)(nil),  // 0: api.battle.v1.CreateWeaponRequest
	(*CreateWeaponReply)(nil),    // 1: api.battle.v1.CreateWeaponReply
	(*UpdateWeaponRequest)(nil),  // 2: api.battle.v1.UpdateWeaponRequest
	(*UpdateWeaponReply)(nil),    // 3: api.battle.v1.UpdateWeaponReply
	(*DeleteWeaponRequest)(nil),  // 4: api.battle.v1.DeleteWeaponRequest
	(*DeleteWeaponReply)(nil),    // 5: api.battle.v1.DeleteWeaponReply
	(*GetWeaponRequest)(nil),     // 6: api.battle.v1.GetWeaponRequest
	(*GetWeaponReply)(nil),       // 7: api.battle.v1.GetWeaponReply
	(*ListWeaponRequest)(nil),    // 8: api.battle.v1.ListWeaponRequest
	(*ListWeaponReply)(nil),      // 9: api.battle.v1.ListWeaponReply
	(*ListWeaponReply_Data)(nil), // 10: api.battle.v1.ListWeaponReply.Data
}
var file_battle_v1_weapon_proto_depIdxs = []int32{
	10, // 0: api.battle.v1.ListWeaponReply.data:type_name -> api.battle.v1.ListWeaponReply.Data
	0,  // 1: api.battle.v1.Weapon.CreateWeapon:input_type -> api.battle.v1.CreateWeaponRequest
	2,  // 2: api.battle.v1.Weapon.UpdateWeapon:input_type -> api.battle.v1.UpdateWeaponRequest
	4,  // 3: api.battle.v1.Weapon.DeleteWeapon:input_type -> api.battle.v1.DeleteWeaponRequest
	6,  // 4: api.battle.v1.Weapon.GetWeapon:input_type -> api.battle.v1.GetWeaponRequest
	8,  // 5: api.battle.v1.Weapon.ListWeapon:input_type -> api.battle.v1.ListWeaponRequest
	1,  // 6: api.battle.v1.Weapon.CreateWeapon:output_type -> api.battle.v1.CreateWeaponReply
	3,  // 7: api.battle.v1.Weapon.UpdateWeapon:output_type -> api.battle.v1.UpdateWeaponReply
	5,  // 8: api.battle.v1.Weapon.DeleteWeapon:output_type -> api.battle.v1.DeleteWeaponReply
	7,  // 9: api.battle.v1.Weapon.GetWeapon:output_type -> api.battle.v1.GetWeaponReply
	9,  // 10: api.battle.v1.Weapon.ListWeapon:output_type -> api.battle.v1.ListWeaponReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_battle_v1_weapon_proto_init() }
func file_battle_v1_weapon_proto_init() {
	if File_battle_v1_weapon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_battle_v1_weapon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_v1_weapon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeaponReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_battle_v1_weapon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battle_v1_weapon_proto_goTypes,
		DependencyIndexes: file_battle_v1_weapon_proto_depIdxs,
		MessageInfos:      file_battle_v1_weapon_proto_msgTypes,
	}.Build()
	File_battle_v1_weapon_proto = out.File
	file_battle_v1_weapon_proto_rawDesc = nil
	file_battle_v1_weapon_proto_goTypes = nil
	file_battle_v1_weapon_proto_depIdxs = nil
}
