// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: bff/v1/bff.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMonsterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMonsterRequest) Reset() {
	*x = GetMonsterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMonsterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonsterRequest) ProtoMessage() {}

func (x *GetMonsterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonsterRequest.ProtoReflect.Descriptor instead.
func (*GetMonsterRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{0}
}

func (x *GetMonsterRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMonsterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetMonsterReply) Reset() {
	*x = GetMonsterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMonsterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonsterReply) ProtoMessage() {}

func (x *GetMonsterReply) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonsterReply.ProtoReflect.Descriptor instead.
func (*GetMonsterReply) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{1}
}

func (x *GetMonsterReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMonsterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMonsterRequest) Reset() {
	*x = ListMonsterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMonsterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonsterRequest) ProtoMessage() {}

func (x *ListMonsterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonsterRequest.ProtoReflect.Descriptor instead.
func (*ListMonsterRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{2}
}

type ListMonsterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ListMonsterReply_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListMonsterReply) Reset() {
	*x = ListMonsterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMonsterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonsterReply) ProtoMessage() {}

func (x *ListMonsterReply) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonsterReply.ProtoReflect.Descriptor instead.
func (*ListMonsterReply) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{3}
}

func (x *ListMonsterReply) GetData() []*ListMonsterReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWeaponRequest) Reset() {
	*x = GetWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponRequest) ProtoMessage() {}

func (x *GetWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponRequest.ProtoReflect.Descriptor instead.
func (*GetWeaponRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{4}
}

func (x *GetWeaponRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetWeaponReply) Reset() {
	*x = GetWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponReply) ProtoMessage() {}

func (x *GetWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponReply.ProtoReflect.Descriptor instead.
func (*GetWeaponReply) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{5}
}

func (x *GetWeaponReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWeaponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWeaponRequest) Reset() {
	*x = ListWeaponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponRequest) ProtoMessage() {}

func (x *ListWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponRequest.ProtoReflect.Descriptor instead.
func (*ListWeaponRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{6}
}

type ListWeaponReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ListWeaponReply_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListWeaponReply) Reset() {
	*x = ListWeaponReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeaponReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponReply) ProtoMessage() {}

func (x *ListWeaponReply) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponReply.ProtoReflect.Descriptor instead.
func (*ListWeaponReply) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{7}
}

func (x *ListWeaponReply) GetData() []*ListWeaponReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListMonsterReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListMonsterReply_Data) Reset() {
	*x = ListMonsterReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMonsterReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonsterReply_Data) ProtoMessage() {}

func (x *ListMonsterReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonsterReply_Data.ProtoReflect.Descriptor instead.
func (*ListMonsterReply_Data) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListMonsterReply_Data) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListMonsterReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWeaponReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListWeaponReply_Data) Reset() {
	*x = ListWeaponReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_bff_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeaponReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponReply_Data) ProtoMessage() {}

func (x *ListWeaponReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponReply_Data.ProtoReflect.Descriptor instead.
func (*ListWeaponReply_Data) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListWeaponReply_Data) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListWeaponReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_bff_v1_bff_proto protoreflect.FileDescriptor

var file_bff_v1_bff_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x75,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2a, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x73, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2a, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xbd, 0x03, 0x0a, 0x03, 0x42, 0x66,
	0x66, 0x12, 0x6f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x72, 0x69, 0x61, 0x2f, 0x62,
	0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x6d, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x72,
	0x69, 0x61, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x6b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e,
	0x12, 0x1c, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x72, 0x69, 0x61, 0x2f, 0x62, 0x66, 0x66, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x69,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19,
	0x12, 0x17, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x72, 0x69, 0x61, 0x2f, 0x62, 0x66, 0x66, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x42, 0x18, 0x5a, 0x16, 0x74, 0x65, 0x72,
	0x72, 0x61, 0x72, 0x69, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bff_v1_bff_proto_rawDescOnce sync.Once
	file_bff_v1_bff_proto_rawDescData = file_bff_v1_bff_proto_rawDesc
)

func file_bff_v1_bff_proto_rawDescGZIP() []byte {
	file_bff_v1_bff_proto_rawDescOnce.Do(func() {
		file_bff_v1_bff_proto_rawDescData = protoimpl.X.CompressGZIP(file_bff_v1_bff_proto_rawDescData)
	})
	return file_bff_v1_bff_proto_rawDescData
}

var file_bff_v1_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bff_v1_bff_proto_goTypes = []interface{}{
	(*GetMonsterRequest)(nil),     // 0: api.bff.v1.GetMonsterRequest
	(*GetMonsterReply)(nil),       // 1: api.bff.v1.GetMonsterReply
	(*ListMonsterRequest)(nil),    // 2: api.bff.v1.ListMonsterRequest
	(*ListMonsterReply)(nil),      // 3: api.bff.v1.ListMonsterReply
	(*GetWeaponRequest)(nil),      // 4: api.bff.v1.GetWeaponRequest
	(*GetWeaponReply)(nil),        // 5: api.bff.v1.GetWeaponReply
	(*ListWeaponRequest)(nil),     // 6: api.bff.v1.ListWeaponRequest
	(*ListWeaponReply)(nil),       // 7: api.bff.v1.ListWeaponReply
	(*ListMonsterReply_Data)(nil), // 8: api.bff.v1.ListMonsterReply.Data
	(*ListWeaponReply_Data)(nil),  // 9: api.bff.v1.ListWeaponReply.Data
}
var file_bff_v1_bff_proto_depIdxs = []int32{
	8, // 0: api.bff.v1.ListMonsterReply.data:type_name -> api.bff.v1.ListMonsterReply.Data
	9, // 1: api.bff.v1.ListWeaponReply.data:type_name -> api.bff.v1.ListWeaponReply.Data
	0, // 2: api.bff.v1.Bff.GetMonster:input_type -> api.bff.v1.GetMonsterRequest
	2, // 3: api.bff.v1.Bff.ListMonster:input_type -> api.bff.v1.ListMonsterRequest
	4, // 4: api.bff.v1.Bff.GetWeapon:input_type -> api.bff.v1.GetWeaponRequest
	6, // 5: api.bff.v1.Bff.ListWeapon:input_type -> api.bff.v1.ListWeaponRequest
	1, // 6: api.bff.v1.Bff.GetMonster:output_type -> api.bff.v1.GetMonsterReply
	3, // 7: api.bff.v1.Bff.ListMonster:output_type -> api.bff.v1.ListMonsterReply
	5, // 8: api.bff.v1.Bff.GetWeapon:output_type -> api.bff.v1.GetWeaponReply
	7, // 9: api.bff.v1.Bff.ListWeapon:output_type -> api.bff.v1.ListWeaponReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bff_v1_bff_proto_init() }
func file_bff_v1_bff_proto_init() {
	if File_bff_v1_bff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bff_v1_bff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMonsterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMonsterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMonsterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMonsterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeaponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeaponReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMonsterReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_bff_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeaponReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bff_v1_bff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_v1_bff_proto_goTypes,
		DependencyIndexes: file_bff_v1_bff_proto_depIdxs,
		MessageInfos:      file_bff_v1_bff_proto_msgTypes,
	}.Build()
	File_bff_v1_bff_proto = out.File
	file_bff_v1_bff_proto_rawDesc = nil
	file_bff_v1_bff_proto_goTypes = nil
	file_bff_v1_bff_proto_depIdxs = nil
}
