// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"fwt/internal/biz"
	"fwt/internal/conf"
	"fwt/internal/data"
	"fwt/internal/server"
	"fwt/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, confData *conf.Data, config *conf.Config, logger log.Logger, contextContext context.Context) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	goodsRepo := data.NewGoodsRepo(dataData, logger)
	goodsUsecase := biz.NewGoodsUsecase(goodsRepo, logger)
	goodsService := service.NewGoodsService(goodsUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, goodsService)
	app := newApp(logger, grpcServer, config, contextContext)
	return app, func() {
		cleanup()
	}, nil
}
