// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"terraria/app/bff/internal/biz"
	"terraria/app/bff/internal/conf"
	"terraria/app/bff/internal/data"
	"terraria/app/bff/internal/server"
	"terraria/app/bff/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	bffRepo := data.NewBffRepo(dataData, logger)
	bffUsecase := biz.NewBffUsecase(bffRepo, logger)
	bffService := service.NewBffService(bffUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, bffService, logger)
	grpcServer := server.NewGRPCServer(confServer, bffService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
