// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"terraria/app/admin/internal/biz"
	"terraria/app/admin/internal/conf"
	"terraria/app/admin/internal/data"
	"terraria/app/admin/internal/server"
	"terraria/app/admin/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	adminRepo := data.NewAdminRepo(dataData, logger)
	adminUsecase := biz.NewAdminUsecase(adminRepo, logger)
	adminService := service.NewAdminService(adminUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, adminService, logger)
	grpcServer := server.NewGRPCServer(confServer, adminService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
